/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/plans/{id}": {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        /** Get a plan by ID */
        get: operations["getById"];
        /** Update a plan (OWNER only) */
        put: operations["update"];
        post: never;
        /** Soft-delete a plan (OWNER only). Existing memberships are unaffected. */
        delete: operations["delete"];
        options: never;
        head: never;
        patch: never;
        trace: never;
    };
    "/api/staff": {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        get: never;
        put: never;
        /**
         * Create a staff account
         * @description Creates a new STAFF user scoped to the caller's gym. gymId is taken from the JWT — never from the request body. Requires OWNER role.
         */
        post: operations["createStaff"];
        delete: never;
        options: never;
        head: never;
        patch: never;
        trace: never;
    };
    "/api/plans": {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        /** List all active plans for this gym */
        get: operations["getAll"];
        put: never;
        /** Create a new subscription plan (OWNER only) */
        post: operations["create"];
        delete: never;
        options: never;
        head: never;
        patch: never;
        trace: never;
    };
    "/api/payments": {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        /** Get paginated payments with optional date and mode filters */
        get: operations["getPayments"];
        put: never;
        /** Record a payment */
        post: operations["createPayment"];
        delete: never;
        options: never;
        head: never;
        patch: never;
        trace: never;
    };
    "/api/payments/{id}/reverse": {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        get: never;
        put: never;
        /** Reverse a payment (OWNER only) */
        post: operations["reversePayment"];
        delete: never;
        options: never;
        head: never;
        patch: never;
        trace: never;
    };
    "/api/members": {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        /**
         * Get members
         * @description Get paginated list of active members, optionally search by name/phone
         */
        get: operations["getMembers"];
        put: never;
        /**
         * Create a new member
         * @description Creates a member and their first membership
         */
        post: operations["createMember"];
        delete: never;
        options: never;
        head: never;
        patch: never;
        trace: never;
    };
    "/api/members/{id}/renew": {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        get: never;
        put: never;
        /** Renew a membership */
        post: operations["renewMembership"];
        delete: never;
        options: never;
        head: never;
        patch: never;
        trace: never;
    };
    "/api/members/{id}/photo": {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        /**
         * Get member photo
         * @description Serves the actual image file securely
         */
        get: operations["getPhoto"];
        put: never;
        /** Upload member photo */
        post: operations["uploadPhoto"];
        delete: never;
        options: never;
        head: never;
        patch: never;
        trace: never;
    };
    "/api/auth/register-gym": {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        get: never;
        put: never;
        /**
         * Register a new gym
         * @description Creates a gym tenant + owner account. Starts a 14-day trial. Returns the gymCode that staff will use to log in.
         */
        post: operations["registerGym"];
        delete: never;
        options: never;
        head: never;
        patch: never;
        trace: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        get: never;
        put: never;
        /**
         * Refresh access token
         * @description Exchanges a valid refresh token for a new access + refresh pair (rotation).
         */
        post: operations["refresh"];
        delete: never;
        options: never;
        head: never;
        patch: never;
        trace: never;
    };
    "/api/auth/login": {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        get: never;
        put: never;
        /**
         * Login
         * @description Provide phone + password + gymCode for OWNER/STAFF. Leave gymCode blank for SUPER_ADMIN login.
         */
        post: operations["login"];
        delete: never;
        options: never;
        head: never;
        patch: never;
        trace: never;
    };
    "/api/attendance/checkin": {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        get: never;
        put: never;
        /** Check in a member (supports QR code) */
        post: operations["checkIn"];
        delete: never;
        options: never;
        head: never;
        patch: never;
        trace: never;
    };
    "/api/admin/gyms/{id}/extend": {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        get: never;
        put: never;
        /** Extend gym subscription */
        post: operations["extendSubscription"];
        delete: never;
        options: never;
        head: never;
        patch: never;
        trace: never;
    };
    "/api/payments/{id}/receipt": {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        /** Download payment receipt as PDF */
        get: operations["getReceiptPdf"];
        put: never;
        post: never;
        delete: never;
        options: never;
        head: never;
        patch: never;
        trace: never;
    };
    "/api/members/{id}": {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        /** Get member details */
        get: operations["getMember"];
        put: never;
        post: never;
        /** Soft delete a member */
        delete: operations["deleteMember"];
        options: never;
        head: never;
        patch: never;
        trace: never;
    };
    "/api/dues": {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        /** Get list of members with pending dues */
        get: operations["getDues"];
        put: never;
        post: never;
        delete: never;
        options: never;
        head: never;
        patch: never;
        trace: never;
    };
    "/api/dashboard": {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        /** Get dashboard metrics */
        get: operations["getDashboard"];
        put: never;
        post: never;
        delete: never;
        options: never;
        head: never;
        patch: never;
        trace: never;
    };
    "/api/attendance": {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        /** Get attendance for a specific date */
        get: operations["getAttendance"];
        put: never;
        post: never;
        delete: never;
        options: never;
        head: never;
        patch: never;
        trace: never;
    };
    "/api/attendance/absent": {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        /** Get members absent for N or more days */
        get: operations["getAbsentMembers"];
        put: never;
        post: never;
        delete: never;
        options: never;
        head: never;
        patch: never;
        trace: never;
    };
    "/api/admin/gyms": {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        /** List all registered gyms */
        get: operations["listGyms"];
        put: never;
        post: never;
        delete: never;
        options: never;
        head: never;
        patch: never;
        trace: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PlanRequest: {
            name: string;
            /** Format: int32 */
            durationDays: number;
            /** Format: int64 */
            pricePaise: number;
        };
        ApiResponsePlanResponse: {
            success: boolean;
            message: string;
            data: components["schemas"]["PlanResponse"];
            error: Record<string, never>;
        };
        PlanResponse: {
            id: string;
            gymId: string;
            name: string;
            /** Format: int32 */
            durationDays: number;
            /** Format: int64 */
            pricePaise: number;
            priceFormatted: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateStaffRequest: {
            name: string;
            phone: string;
            password: string;
        };
        ApiResponseVoid: {
            success: boolean;
            message: string;
            data: Record<string, never>;
            error: Record<string, never>;
        };
        CreatePaymentRequest: {
            memberId: string;
            membershipId: string;
            /** Format: int64 */
            memberName: string;
            amountPaise: number;
            mode: string;
            /** Format: date */
            paymentDate: string;
            reason: string;
        };
        ApiResponsePaymentResponse: {
            success: boolean;
            message: string;
            data: components["schemas"]["PaymentResponse"];
            error: Record<string, never>;
        };
        PaymentResponse: {
            id: string;
            gymId: string;
            memberId: string;
            membershipId: string;
            /** Format: int64 */
            memberName: string;
            amountPaise: number;
            mode: string;
            /** Format: date-time */
            paidAt: string;
            receiptNo: string;
            type: string;
            reversalOfId: string;
            reason: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateMemberRequest: {
            name: string;
            phone: string;
            gender: string;
            /** Format: date */
            dob: string;
            address: string;
            planId: string;
            /** Format: date */
            startDate: string;
        };
        ApiResponseMemberResponse: {
            success: boolean;
            message: string;
            data: components["schemas"]["MemberResponse"];
            error: Record<string, never>;
        };
        MemberResponse: {
            id: string;
            gymId: string;
            memberCode: string;
            name: string;
            phone: string;
            gender: string;
            /** Format: date */
            dob: string;
            address: string;
            photoUrl: string;
            status: string;
            /** Format: date */
            currentExpiry: string;
            /** Format: int64 */
            currentDuePaise: number;
            /** Format: date */
            lastAttendanceDate: string;
            currentMembership: components["schemas"]["MembershipResponse"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MembershipResponse: {
            id: string;
            gymId: string;
            memberId: string;
            planId: string;
            planName: string;
            /** Format: int64 */
            totalPaise: number;
            /** Format: int64 */
            paidPaise: number;
            /** Format: int64 */
            duePaise: number;
            /** Format: date */
            startDate: string;
            /** Format: date */
            expiryDate: string;
            status: string;
            /** Format: date-time */
            createdAt: string;
        };
        RenewMembershipRequest: {
            planId: string;
            /** Format: date */
            startDate: string;
        };
        ApiResponseMembershipResponse: {
            success: boolean;
            message: string;
            data: components["schemas"]["MembershipResponse"];
            error: Record<string, never>;
        };
        ApiResponseString: {
            success: boolean;
            message: string;
            data: string;
            error: Record<string, never>;
        };
        RegisterGymRequest: {
            gymName: string;
            gymPhone: string;
            gymEmail: string;
            gymAddress: string;
            ownerName: string;
            ownerPhone: string;
            password: string;
        };
        ApiResponseGymResponse: {
            success: boolean;
            message: string;
            data: components["schemas"]["GymResponse"];
            error: Record<string, never>;
        };
        GymResponse: {
            gymId: string;
            gymName: string;
            gymCode: string;
            ownerName: string;
            ownerPhone: string;
            /** Format: date-time */
            trialEndsAt: string;
        };
        RefreshTokenRequest: {
            refreshToken: string;
        };
        ApiResponseTokenResponse: {
            success: boolean;
            message: string;
            data: components["schemas"]["TokenResponse"];
            error: Record<string, never>;
        };
        TokenResponse: {
            accessToken: string;
            refreshToken: string;
            tokenType: string;
            /** Format: int64 */
            expiresIn: number;
            userId: string;
            gymId: string;
            role: string;
        };
        LoginRequest: {
            phone: string;
            password: string;
            gymCode: string;
        };
        CheckInRequest: {
            memberId: string;
            memberCode: string;
        };
        ApiResponseCheckInResponse: {
            success: boolean;
            message: string;
            data: components["schemas"]["CheckInResponse"];
            error: Record<string, never>;
        };
        CheckInResponse: {
            id: string;
            memberId: string;
            memberName: string;
            /** Format: date */
            date: string;
            checkInTime: components["schemas"]["LocalTime"];
            membershipExpiredWarning: boolean;
        };
        LocalTime: {
            /** Format: int32 */
            hour: number;
            /** Format: int32 */
            minute: number;
            /** Format: int32 */
            second: number;
            /** Format: int32 */
            nano: number;
        };
        ExtendSubscriptionRequest: {
            /** Format: int32 */
            daysToAdd: number;
        };
        ApiResponseGym: {
            success: boolean;
            message: string;
            data: components["schemas"]["Gym"];
            error: Record<string, never>;
        };
        Gym: {
            id: string;
            name: string;
            ownerName: string;
            phone: string;
            address: string;
            logoUrl: string;
            gymCode: string;
            status: string;
            subscriptionPlan: string;
            /** Format: date */
            subscriptionValidTill: string;
            allowExpiredCheckin: boolean;
            /** Format: int32 */
            reminderDaysBefore: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
        };
        ApiResponseListPlanResponse: {
            success: boolean;
            message: string;
            data: components["schemas"]["PlanResponse"][];
            error: Record<string, never>;
        };
        ApiResponsePagedResponsePaymentResponse: {
            success: boolean;
            message: string;
            data: components["schemas"]["PagedResponsePaymentResponse"];
            error: Record<string, never>;
        };
        PagedResponsePaymentResponse: {
            content: components["schemas"]["PaymentResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
            last: boolean;
        };
        ApiResponsePagedResponseMemberResponse: {
            success: boolean;
            message: string;
            data: components["schemas"]["PagedResponseMemberResponse"];
            error: Record<string, never>;
        };
        PagedResponseMemberResponse: {
            content: components["schemas"]["MemberResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
            last: boolean;
        };
        ApiResponsePagedResponseMemberDueResponse: {
            success: boolean;
            message: string;
            data: components["schemas"]["PagedResponseMemberDueResponse"];
            error: Record<string, never>;
        };
        MemberDueResponse: {
            memberId: string;
            memberCode: string;
            memberName: string;
            phone: string;
            membershipId: string;
            /** Format: int64 */
            totalDuePaise: number;
        };
        PagedResponseMemberDueResponse: {
            content: components["schemas"]["MemberDueResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
            last: boolean;
        };
        ApiResponseDashboardResponse: {
            success: boolean;
            message: string;
            data: components["schemas"]["DashboardResponse"];
            error: Record<string, never>;
        };
        DashboardResponse: {
            /** Format: int64 */
            activeMembers: number;
            /** Format: int64 */
            todayCollection: number;
            /** Format: int64 */
            monthCollection: number;
            /** Format: int64 */
            expiringSoon: number;
            /** Format: int64 */
            newJoinings: number;
            /** Format: int64 */
            todayAttendance: number;
            /** Format: int64 */
            totalDue: number;
        };
        ApiResponsePagedResponseAttendanceRecordResponse: {
            success: boolean;
            message: string;
            data: components["schemas"]["PagedResponseAttendanceRecordResponse"];
            error: Record<string, never>;
        };
        AttendanceRecordResponse: {
            id: string;
            memberId: string;
            memberName: string;
            memberCode: string;
            /** Format: date */
            date: string;
            checkInTime: components["schemas"]["LocalTime"];
        };
        PagedResponseAttendanceRecordResponse: {
            content: components["schemas"]["AttendanceRecordResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
            last: boolean;
        };
        AbsentMemberResponse: {
            memberId: string;
            memberCode: string;
            memberName: string;
            phone: string;
            /** Format: date */
            lastAttendanceDate: string;
            /** Format: int64 */
            daysAbsent: number;
        };
        ApiResponsePagedResponseAbsentMemberResponse: {
            success: boolean;
            message: string;
            data: components["schemas"]["PagedResponseAbsentMemberResponse"];
            error: Record<string, never>;
        };
        PagedResponseAbsentMemberResponse: {
            content: components["schemas"]["AbsentMemberResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
            last: boolean;
        };
        ApiResponseListGym: {
            success: boolean;
            message: string;
            data: components["schemas"]["Gym"][];
            error: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getById: {
        parameters: {
            query: never;
            header: never;
            path: {
                id: string;
            };
            cookie: never;
        };
        requestBody: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePlanResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query: never;
            header: never;
            path: {
                id: string;
            };
            cookie: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePlanResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query: never;
            header: never;
            path: {
                id: string;
            };
            cookie: never;
        };
        requestBody: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    createStaff: {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStaffRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getAll: {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        requestBody: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPlanResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePlanResponse"];
                };
            };
        };
    };
    getPayments: {
        parameters: {
            query: {
                startDate: string;
                endDate: string;
                mode: string;
                page: number;
                size: number;
            };
            header: never;
            path: never;
            cookie: never;
        };
        requestBody: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePagedResponsePaymentResponse"];
                };
            };
        };
    };
    createPayment: {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePaymentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePaymentResponse"];
                };
            };
        };
    };
    reversePayment: {
        parameters: {
            query: {
                notes: string;
            };
            header: never;
            path: {
                id: string;
            };
            cookie: never;
        };
        requestBody: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePaymentResponse"];
                };
            };
        };
    };
    getMembers: {
        parameters: {
            query: {
                search: string;
                page: number;
                size: number;
            };
            header: never;
            path: never;
            cookie: never;
        };
        requestBody: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePagedResponseMemberResponse"];
                };
            };
        };
    };
    createMember: {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemberRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMemberResponse"];
                };
            };
        };
    };
    renewMembership: {
        parameters: {
            query: never;
            header: never;
            path: {
                id: string;
            };
            cookie: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenewMembershipRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMembershipResponse"];
                };
            };
        };
    };
    getPhoto: {
        parameters: {
            query: never;
            header: never;
            path: {
                id: string;
            };
            cookie: never;
        };
        requestBody: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    uploadPhoto: {
        parameters: {
            query: never;
            header: never;
            path: {
                id: string;
            };
            cookie: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    registerGym: {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterGymRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGymResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTokenResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTokenResponse"];
                };
            };
        };
    };
    checkIn: {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCheckInResponse"];
                };
            };
        };
    };
    extendSubscription: {
        parameters: {
            query: never;
            header: never;
            path: {
                id: string;
            };
            cookie: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtendSubscriptionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGym"];
                };
            };
        };
    };
    getReceiptPdf: {
        parameters: {
            query: never;
            header: never;
            path: {
                id: string;
            };
            cookie: never;
        };
        requestBody: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string[];
                };
            };
        };
    };
    getMember: {
        parameters: {
            query: never;
            header: never;
            path: {
                id: string;
            };
            cookie: never;
        };
        requestBody: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMemberResponse"];
                };
            };
        };
    };
    deleteMember: {
        parameters: {
            query: never;
            header: never;
            path: {
                id: string;
            };
            cookie: never;
        };
        requestBody: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getDues: {
        parameters: {
            query: {
                page: number;
                size: number;
            };
            header: never;
            path: never;
            cookie: never;
        };
        requestBody: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePagedResponseMemberDueResponse"];
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        requestBody: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDashboardResponse"];
                };
            };
        };
    };
    getAttendance: {
        parameters: {
            query: {
                date: string;
                page: number;
                size: number;
            };
            header: never;
            path: never;
            cookie: never;
        };
        requestBody: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePagedResponseAttendanceRecordResponse"];
                };
            };
        };
    };
    getAbsentMembers: {
        parameters: {
            query: {
                days: number;
                page: number;
                size: number;
            };
            header: never;
            path: never;
            cookie: never;
        };
        requestBody: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePagedResponseAbsentMemberResponse"];
                };
            };
        };
    };
    listGyms: {
        parameters: {
            query: never;
            header: never;
            path: never;
            cookie: never;
        };
        requestBody: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListGym"];
                };
            };
        };
    };
}
